### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Abdul-Kaium5** [jarylc/cf-workers-chatgpt-telegram-bot#2]
✘ [ERROR] A request to the Cloudflare API (/accounts/a2c7bf8fee1e163f818a4bbf6fccd552/workers/scripts/cf-workers-chatgpt-telegram-bot) failed.

  No KV namespace found with ID a2c7bf8fee1e163f818a4bbf6fccd552 [code: 10041]

**Comment by valokobito** [comment]
@ab-kaium 

This is how to fix it:
1. Goto [https://dash.cloudflare.com](https://dash.cloudflare.com) -> "Workers & Pages" -> "KV"
2. Create a namespace with the name `CHATGPT_TELEGRAM_BOT_KV`. 
3. After creating, copy its id.
4. Goto to the project you cloned to you computer.
5. Open file `wrangler.toml`.
6. Replace the id with the id you copied in your Cloudflare dashboard.
7. Run `npx wrangler publish` again.
