### ISSUE TITLE
Can I Deploy On Cloudlafre Pages?

### ISSUE THREAD

**Issue by JohanChungus** [jarylc/cf-workers-chatgpt-telegram-bot#4]
if can I need know can you give me the example of the weebhook

**Comment by jarylc** [comment]
I'm pretty sure you can, but I don't see a reason to as there is no frontend served nor caching needed and this can simply be deployed on Workers alone.

Steps are at the bottom of the README.md file

**Comment by JohanChungus** [comment]
I try deploy using connect to git and set the environment 
before that I have changed the username in wrangler.toml
OPENAI_API_KEY=sk-xxxxxxxxxxxxxxx
TELEGRAM_BOT_TOKEN=6046×××××:××××××××××
and I automatically deploy
I Visit The Site And Its Say HTTP_ERROR_404
here my site
https://cf-workers-chatgpt-telegram-bot.pages.dev/

**Comment by jarylc** [comment]
When you do `wrangler deploy`, it should show the link? You can click that to test it. That link you sent doesn't seem right as I don't see your namespace.

Honestly you should be able to follow step 11 and your bot should work

> Replace `{TELEGRAM_BOT_TOKEN}` and `{WORKERS_NAMESPACE}` on the following `https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/setWebhook?&allowed_updates=%5B%22message%22%2C%22inline_query%22%2C%22callback_query%22%5D&url=https%3A%2F%2Fcf-workers-chatgpt-telegram-bot.{WORKERS_NAMESPACE}.workers.dev%2F{TELEGRAM_BOT_TOKEN}` and access it on your browser

Assuming you have deployed it correctly.

**Comment by JohanChungus** [comment]
No thats right url,Hmm I Think Pages its different between Workers When Using The Pages Im not using wrangler its automatically deploy
![Screenshot_20230401-102439_Chrome](https://user-images.githubusercontent.com/113217515/229263583-0ef4bcd6-1a5f-445b-8e4a-b3551d8be1b3.png)
![Screenshot_20230401-102355_Chrome](https://user-images.githubusercontent.com/113217515/229263588-306126bb-b43f-4035-a807-da99c21c6b5a.png)

**Comment by jarylc** [comment]
Huh that's weird, why is it being deployed to pages.

Did you add the repository on Cloudflare Pages UI or run the Wrangler CLI commands on the README?

This project does not support adding the repository Cloudflare Pages UI. You have to run the terminal commands.

**Comment by JohanChungus** [comment]
I just fork and edit wrangler.toml then deploy. Hmm I Think Im Wrong, I Should Be Deploy On Workers Not Pages
